name: Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source: https://nuget.pkg.github.com/GasiorowskiPiotr/index.json 
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release -o pkgs -p:PackageVersion=0.1.$GITHUB_RUN_NUMBER
    - name: Publish
      run: dotnet nuget push -s Source "pkgs/*.nupkg" --no-symbols true
